### ISSUE TITLE
WHB04B-6 using in other project

### ISSUE THREAD

**Issue by alkabal** [rubienr/bbb-linuxcnc-config#1]
Hi

This is not a real issue but i like to add WHB04B-6 to my own config (furaday cape), after many time shearching over the web i have found your fork with some file for this device.

Can you help me to understand i think the last file is only a link but i dont found the real file in any folder. (xhc-whb04b-6.tcl)

I have not ordered this unit for the moment i like to found how to make it work before.(but not wait more if your dile work)

Best regards, Aurélien

**Comment by rubienr** [comment]
Hi Aurélien,

the symlink removal has been forgotten since the file it was pointing at, has been removed (see this [cleanup](https://github.com/rubienr/machinekit/commit/6774118c25a5b8ffce35495fcec2da0cbf2b0384) commit).
If you are looking for the component's source code, it can be found [here](https://github.com/rubienr/machinekit/tree/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6).
At the moment I cannot provide you any complete and up to date component documentation, although writing the [man page](https://github.com/rubienr/machinekit-docs/blob/master/docs/man/man1/xhc-whb04b-6.asciidoc) has been started.
Be aware that the source is still under development even though I consider the component being stable.

hth & br, rr

**Comment by alkabal** [comment]
Hi
Ok i can try to compile driver with your src thanks.

You plan to continu developing this device ? i can order today if you can confirm this.
I'm windows userso i can try to sniff the USB protocol if this is possible without // port or usb/ethernet card for this software ?

Best regards, thank you

**Comment by rubienr** [comment]
Hi,

The userspace component for whb04b-6 can bee seen as feature complete. All buttons and features are working such as:
* displaying (see also this [illustration](https://github.com/rubienr/machinekit/blob/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6/README.md#display-examples))
  * machine/work piece coordinates
  * step size, speed mode
  * if machine is in reset state
  * feed rate
  * spindle speed
* buttons
  * z-probing
  * homing
  * move to machine home position
  * move to safe-z position
  * in-/decrement feed rate or spindle speed
  * start/stop spindle
  * change spindle direction
  * start/stop/resume program
  * stop machine or resume from reset condition
  * meta buttons: `Fn` + arbitrary button
* jog dial for all six axis in
  * speed mode: as long you turn the wheel, as long the machine moves at the currently configured feed rate
  * step mode: as many steps you turn the wheel, as many steps the machine will drive at the currently configured step size

Since I use this jog dial personally, I plan maintain the source for a while. 
If you want to have insight into the protocol, [this site](https://github.com/rubienr/machinekit/blob/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6/README.md) -- logging thoughts, what has been done and what is still open -- may be of interest. For example the CRC for USB packages has not been implemented.

**Comment by alkabal** [comment]
Oh great !

And for compiling ? sorry noob inside with linux !

**Comment by alkabal** [comment]
Hi i have try to git your repo and make the necessary changer for trying to compile but for now i can't do this needed part :
http://www.machinekit.io/docs/getting-started/APT-packages-jessie/

can you share needed files ?

i hope to understand later how to compile myself.

Best regards

**Comment by alkabal** [comment]
Hi

it is posssible to compile your driver direct from BBB without compiling all machinekit ?

Br

**Comment by alkabal** [comment]
Hi again

i hope i have compil correctly, now i try to make it work

thanks for sharing your project.

**Comment by alkabal** [comment]
for now i have error but the pendant is not delivered for now so i don't know if the error is only because missing unit. (is planned tomorrow or really soon)

hal   initialize HAL component in HAL mode xhc-whb04b-6 ... ok
hal   initialize shared HAL memory for component id  38 ... failed to allocate HAL memory
xhc-whb04b-6.hal:8: xhc-whb04b-6 exited without becoming ready

**Comment by rubienr** [comment]
For compiling machinekit follow [this site](http://www.machinekit.io/docs/developing/machinekit-developing/). After one compile run, if you change the source code, you may compile the driver only by entering the source directory and run the xhc-whb04b-6 make target via `make ../xhc-whb04b-6`. This also holds for compiling the component only.

The error message says that shared memory could not be allocated. This memory is the connection interface in between the component and other HAL components. It is only available if the component is started by Machinekit in HAL mode (xhc-whb04b-6 -H). Otherwise, if you start the component manually on the command line, you need to remove the -H argument (xhc-whb04b-6).

Keep me posted!

**Comment by alkabal** [comment]
many thanks for reply

first :
i have compiled your driver inside the new machinekit git and have a binary 1248ko.
Try to compile only driver with your instruction :
cd /home/machinekit/machinekit/src
make ../xhc-whb04b-6 
no rules for make ../xhc-whb04b-6 

two:
From your fork compilation fail
Compiling machinetalk/lib/mk_service.cc
In file included from machinetalk/lib/mk_service.cc:9:0:
machinetalk/include/mk-service.hh:19:5: error: ‘zctx_t’ does not name a type
     zctx_t        *z_context;

three :
i have copy past xhc-whb04b-6 from /bin to /usr/bin
make chmod +x xhc-whb04b-6
copy halui to my ini from your example-configuration.md
create rules /etc/udev/rules.d/99-xhc-whb04b-6.rules




But now i think is only configuration hal issue and need to adapt section to my hal
# Other components
# Spindle 


with DEBUG=5 is better to understand what append.


Thanks a lot

**Comment by alkabal** [comment]
Hi

I have play a little with your good driver ! for now seem to be work fine for that i have configured correctly.

I have some trouble for understand how to connect spindle on/off and choose default speed at start (for gui i have DEFAULT_SPINDLE_SPEED = 120)

(spindle is stopped) with XHC press start/stop spindle make GUI change ( - and + appears ) but does not move without incresing speed by macro (i have also a spindle relay that is only activated after increase speed)

(spindle is sarted) with XHC i can stop spindle and relay but GUI is not updated again - and + button stay on screen

I have some trouble for understand this HAL parts and found how it work :

```
net  pdnt.button.s-on-off           whb.button.s-on-off
net  spindle.start                        halui.spindle.start     
net  spindle.is-on                       whb.halui.spindle.is-on
net  spindle.stop                        whb.halui.spindle.stop            `halui.spindle.stop
```

can you help me tiny ?

Best regards, another thanks for your great driver !

**Comment by alkabal** [comment]
In reality some time the GUI switch correctly between on/off after clic start stop spindle from XHC, so is there a debounce problem possible ?


it is normal to have 2 mhal headers for macro8 ? (i think hardcoded reverse spindle)
https://github.com/rubienr/machinekit/blob/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6/pendant.cc#L1251
https://github.com/rubienr/machinekit/blob/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6/pendant.cc#L1414


From your src folder config exemple
whb.halui.spindle.start does not exist in src code.

**Comment by alkabal** [comment]
Now is ok i have found the good way for GUI switching spindle on/off from XHC

Only speed at spindle start is not solved for now

I see macro8 is hardcoded for reverse spindle but not documented (i know job is not done 100% is juste for reporting info)

Best regards

Ps : it is possible to have angular value displayed for axis A ?

**Comment by rubienr** [comment]
* macro-8
Fortunately the documentation and source did it to [upstream](http://www.machinekit.io/docs/drivers/xhc-whb04b-6/). As you correctly figured out, I mistakenly did not mention this in the documentation. 
* angular value
Whatever you write to whb.halui.axis.N.pos-feedback (float, in) is displayed on the screen. Again I see  several pins are missing in the documentation. Sorry for that. Thanks for the support!
* whb.halui.spindle.start does not exist in src code
For me it did the trick with these signals only (which is handled [here](https://github.com/rubienr/machinekit/blob/feature-xhc-whb04b-6/src/hal/user_comps/xhc-whb04b-6/hal.cc#L1122)). However, I should pull a new pin out `whb.spindle.start` as you suggest.
    ```
    net  spindle.stop       halui.spindle.stop
    net  spindle.forward    halui.spindle.forward
    net  spindle.reverse    halui.spindle.reverse
    ```

Will be fixed in week 52 or weeks 1-2 2019. Thank you for the advice!

**Comment by alkabal** [comment]
Hi

Many thanks for all your work I check ASAP new release machinekit with your driver included.

Br I hope you a good end of the year

**Comment by rubienr** [comment]
* implemented `whb.halui.spindle.start` as requested
* added to documentation:
  * missing description of pins/signals
  * HAL example
  * display description (what can be displayed)

See source pull request [1] and documentation pull request [2].

[1] https://github.com/machinekit/machinekit/pull/1433
[2] https://github.com/machinekit/machinekit-docs/pull/296
